name: CD

on:
  workflow_run:
    workflows: ["CI"]   # ci.yml
    types:
      - completed # solamente si se completa, ejecuta el job de deploy

jobs:
  deploy:
    name: Render Deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - 
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}&imageUrl=docker.io/${{ secrets.DOCKER_USERNAME }}/tp-devops-app:${{ github.sha }}"
